# patch http://localhost:4004/customer/Customer(ID=03d6cdea-6957-42f3-99e7-9c90cf5dd220,IsActiveEntity=false)/ToOpportunities(ID=3f85c833-e380-49e1-bbb4-9713a085bb47,IsActiveEntity=true)
# Content-Type: application/json

# {
#  "Subject" : "test delete http1234",
#  "Customer_ID" : "83c01ee5-d759-4b99-bf3d-9d9ca9202c9d"
# }

POST  http://localhost:4004/request-approval/RequestApproval(ID=233f48b4-5fa1-4aab-b1f8-193c56e41149,IsActiveEntity=true)/RequestApprovalService.reject
Content-Type: application/json

{

}